spring.application.name=LibraryManagementSystem1
#spring.datasource.url= jdbc:mysql://localhost:3306/Librariry?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=ROOT

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_Library_Management_System?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=freedb_udaychandhar
spring.datasource.password=tAr3XwwW!zBU!SE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udaychandhar123@gmail.com
spring.mail.password=lpmx ppdl umnf nrki
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
